spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:pet_shop}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  address: ${SERVER_ADDRESS:0.0.0.0}
