spring:
  application:
    name: pet-shop-backend
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

server:
  port: ${SERVER_PORT:8080}
  address: ${SERVER_ADDRESS:127.0.0.1}
  servlet:
    context-path: /happy-pet-shop

jwt:
  key: "ZXZlbnR0aHJlYWRvbGRub25lZmVuY2VmYWlybHl0b3dlcmFiaWxpdHlmaW5kYmFsbHM="
  expiration-time: 3600 #seconds
  refreshExpiration-time: 604800 #seconds
