spring:
    application:
        name: happy-pet-shop

    datasource:
        url: "jdbc:postgresql://localhost:5432/happy_pet_shop"
        username: root
        password: root
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true

server:
    port: 8080
    servlet:
        context-path: /happy-pet-shop

jwt:
    key: "ZXZlbnR0aHJlYWRvbGRub25lZmVuY2VmYWlybHl0b3dlcmFiaWxpdHlmaW5kYmFsbHM="
    expiration-time: 3600 #seconds
    refreshExpiration-time: 604800 #seconds